packages/svelteui-core/package.json, packages/svelteui-core/src/lib/Switch/Switch.styles.ts, packages/svelteui-core/src/lib/Switch/Switch.svelte, packages/svelteui-core/src/lib/index.ts, packages/svelteui-core/src/routes/index.svelte
Switch component, inspired by the one in the mantine library - https://mantine.dev/core/switch/.
https://user-images.githubusercontent.com/25725586/160872989-52bf1481-de5b-4774-a905-5fe1cb77753a.mp4
Switch examples:
```svelte
<div style="display: flex; flex-direction: column; flex: 1; height: 100px; justify-content: space-between;">
<Switch label={"This is a label"} onLabel="ON" offLabel="OFF" on:change={(e) => console.log("CHECK", e)}/>
<Switch label={"I agree with the conditions I did not read"} size={"lg"}/>
<Switch bind:checked label={"This is already checked"} />
</div>
```
Would like to open discussion, since I used hardcoded colors, which will not match the active theme.
=> New component `Switch`

.github/PULL_REQUEST_TEMPLATE.md
=> Pull Request template

.husky/pre-commit, .husky/pre-push, packages/svelteui-actions/.svelte-kit/tsconfig.json, packages/svelteui-utilities/.svelte-kit/tsconfig.json
=> Next minor

scripts/utils/version.ts
Fix problem in check in `updateVersion` function that was causing the peerDependencies and dependencies to not be bumped.
=> [core] bump script: fix logic in 'updateVersion' function

packages/svelteui-core/src/lib/components/Checkbox/Checkbox.styles.ts, packages/svelteui-core/src/lib/components/Checkbox/Checkbox.svelte, packages/svelteui-core/src/lib/components/Checkbox/CheckboxIcon.svelte, packages/svelteui-core/src/lib/components/Checkbox/index.ts, packages/svelteui-core/src/lib/components/Input/Input.svelte, packages/svelteui-core/src/lib/components/index.ts, packages/svelteui-core/src/routes/index.svelte
Added Checkbox component
- styling
- support for indeterminate state and icon
- support icon override
https://user-images.githubusercontent.com/25725586/167189315-dce314fb-8212-45f0-8d40-57ffd71f93e2.mp4
Dark theme:
=> [@svelteui/core] Checkbox component

README.md
:warning: :warning: This is the most important PR :warning: :warning: 
JK, just fixing some typos and removing all periods from bullet points, since it was not the same for all
=> [core] fix typo + maintain period standard

.config/cz-config.js, .config/package.json, package-lock.json, package.json
=> [core]: added commitizen

README.md, docs/src/includes/opengraph.svelte, docs/svelte-docs.config.js, packages/svelteui-actions/README.md, packages/svelteui-core/README.md, packages/svelteui-dates/README.md, packages/svelteui-demos/README.md, packages/svelteui-motion/README.md, packages/svelteui-prism/README.md, packages/svelteui-utilities/README.md, packages/svelteui-utilities/src/lib/dist/functions/hash/hash.ts
=> [docs]: more link corrections

docs/src/pages/actions/use-long-press.md, packages/svelteui-actions/src/lib/dist/use-long-press/use-long-press.ts
* Added touch support to `longpress` action
=> [@svelteui/actions] Added `longpress` touch support

package-lock.json, packages/svelteui-demos/README.md, packages/svelteui-demos/src/lib/components/CodeDemo/CodeDemo.svelte, packages/svelteui-demos/src/lib/components/Configurator/Configurator.svelte, packages/svelteui-demos/src/lib/components/Configurator/controls/NumberControl.svelte, packages/svelteui-demos/src/lib/examples/Configurator/Basic.svelte, packages/svelteui-demos/src/lib/examples/Configurator/Multiline.svelte, packages/svelteui-demos/src/lib/types.ts
I added the ability to auto-generate the code templates.
Now you can add `codeTemplate` as object, code template will be generated based on that.
```
export const configuration: ConfiguratorDemoConfiguration = {
codeTemplate: { component: 'Button', from: '@svelteuidev/core' },
...
}
```
If you need more granular control on `codeTemplate` you still can declare function there.
```
const codeTemplate = (props: string) => `
<script>
import { NativeSelect, Center } from '@svelteuidev/core';
export let props: any = {};
<\/script>
<div>
<NativeSelect
value={1}
data={[
{ label: 'Option 1', value: 1 },
{ label: 'Option 2', value: 2 },
{ label: 'Option 3', value: 3 }
]}${props}
/>
</div>
`;
export const configuration: ConfiguratorDemoConfiguration = {
codeTemplate,
...
};
```
* NumberInput dispatch …
=> Demos auto generated code templates

package-lock.json, packages/svelteui-composables/package.json, packages/svelteui-demos/README.md
* Update root package-lock.json (to contain composables)
* Pretty changes to demos README
* Removed testing scripts from composables for now
=> [core] fix failing CI

docs/src/includes/sidebar.md, docs/src/pages/core/affix.md, docs/src/pages/core/burger.md, packages/svelteui-demos/src/lib/demos/core/Affix/Affix.demo.usage.svelte, packages/svelteui-demos/src/lib/demos/core/Affix/index.ts, packages/svelteui-demos/src/lib/demos/core/Burger/Burger.demo.color.svelte, packages/svelteui-demos/src/lib/demos/core/Burger/Burger.demo.size.svelte, packages/svelteui-demos/src/lib/demos/core/Burger/Burger.demo.usage.svelte, packages/svelteui-demos/src/lib/demos/core/Burger/index.ts, packages/svelteui-demos/src/lib/index.ts
* Documentation and demos for `Affix` and `Burger`
https://user-images.githubusercontent.com/25725586/171750858-34a62941-009a-42c2-b942-4948ebd79ac2.mp4
=> [docs] Documentation for Affix and Burger

docs/src/includes/sidebar.md, docs/src/pages/composables/use-hot-key.md, docs/src/pages/core/center.md, docs/src/pages/core/unstyled-button.md, packages/svelteui-demos/src/lib/demos/composables/actions/index.ts, packages/svelteui-demos/src/lib/demos/composables/actions/use-hot-key/index.ts, packages/svelteui-demos/src/lib/demos/composables/actions/use-hot-key/usage.svelte, packages/svelteui-demos/src/lib/demos/core/UnstyledButton/UnstyledButton.demo.usage.svelte, packages/svelteui-demos/src/lib/demos/core/UnstyledButton/index.ts, packages/svelteui-demos/src/lib/index.ts
* Documentation for `UnstyledButton` and `hotkey` and respective demos
* Fixed center documentation category
=> [docs] Documentation for UnstyledButton and hotkey action

packages/svelteui-core/src/pages/Layout/HeadContent.svelte
solve : (Type '(node: HTMLElement, hotkeys: HotkeyItem[]) => { update?: ((parameters: any) => any) | undefined; destroy?: (() => void) | undefined; }' is not assignable to type 'SvelteActionType<any>'.) 
and using the code on the sample page.
=> [@svelteui/core]solve not assignable error in core header file

package-lock.json, packages/svelteui-core/package-lock.json, packages/svelteui-core/package.json, packages/svelteui-core/src/lib/components/Popper/Popper.styles.ts, packages/svelteui-core/src/lib/components/Popper/Popper.svelte, packages/svelteui-core/src/routes/index.svelte
Migrated Popper implementation to [floating-ui](https://floating-ui.com) using their Vanilla DOM positioning engine. This implementation now contains way less bugs, which is a significant improvement 😅 
https://user-images.githubusercontent.com/25725586/172197169-4ebf4fd7-23e5-436d-9d84-6b5796e32672.mov
=> [@svelteui/core] Popper migration to floating UI

.github/workflows/main.yml, packages/svelteui-core/src/lib/components/NativeSelect/NativeSelect.svelte
Small change that makes NativeSelect reactive to data prop changes
=> [@svelteui/core]: NativeSelect data prop is now reactive

packages/svelteui-core/src/lib/components/Button/UnstyledButton/UnstyledButton.svelte, packages/svelteui-core/src/lib/components/NativeSelect/NativeSelect.svelte, packages/svelteui-core/src/lib/components/Switch/Switch.styles.ts, packages/svelteui-core/src/lib/components/Switch/Switch.svelte, packages/svelteui-core/src/lib/styles/engine/create-styles.ts, packages/svelteui-core/src/routes/index.svelte
=> [Next minor]: update main with new changes

docs/decs.d.ts, docs/package-lock.json, docs/package.json, docs/src/components/homepage/HomePageExample.svelte, docs/src/components/homepage/_Card.svelte, docs/src/examples.css, docs/src/pages/changelog/v0-6-5.md, docs/src/theme.css, docs/src/theme/components/Example.svelte, docs/src/theme/components/Layout.svelte, docs/src/theme/components/Properties.svelte, docs/src/theme/info.md, docs/src/theme/islands/Banner/Banner.styles.js, docs/src/theme/islands/Banner/Banner.svelte, docs/src/theme/islands/Banner/index.js, docs/src/theme/islands/index.js, docs/src/theme/style.css, docs/src/theme/styles/highlight.css, docs/src/theme/styles/layout.css, docs/src/theme/styles/typography.css, docs/src/theme/utils/index.js, docs/src/theme/utils/link-actions.js, docs/svelte-docs.config.js, package.json, packages/svelteui-demos/src/lib/demos/core/Card/Card.demo.usage.svelte, scripts/git/discard.sh
=> [docs] migrated from node_modules theme to local theme

package-lock.json, packages/svelteui-composables/src/lib/utilities/index.ts, packages/svelteui-composables/src/lib/utilities/use-element-size/index.ts, packages/svelteui-composables/src/lib/utilities/use-element-size/use-element-size.ts
Added a `useElementSize` utility following the fashion of `useMousePosition` and `useViewPortSize` utilities.
=> [@svelteuidev/composables]: new useElementSize 

.github/workflows/main.yml, package-lock.json, packages/svelteui-core/src/lib/components/Button/Button.svelte
Cache global cache directory (setup-node), node modules and the generated packages in github workflow.
=> [core]: github workflow cache for node modules and dependencies

docs/src/includes/sidebar.md, docs/src/pages/core/alert.md, packages/svelteui-core/src/lib/components/ActionIcon/ActionIcon.svelte, packages/svelteui-core/src/lib/components/Alert/Alert.styles.ts, packages/svelteui-core/src/lib/components/Alert/Alert.svelte, packages/svelteui-core/src/lib/components/Alert/Alert.test.ts, packages/svelteui-core/src/lib/components/Alert/index.ts, packages/svelteui-core/src/lib/components/index.ts, packages/svelteui-core/src/lib/styles/theme/utils/get-variant-theme/get-variant-theme.ts, packages/svelteui-core/src/routes/index.svelte, packages/svelteui-demos/src/lib/demos/core/Alert/Alert.demo.configurator.svelte, packages/svelteui-demos/src/lib/demos/core/Alert/index.ts, packages/svelteui-demos/src/lib/index.ts
- component
- demo
- docs
:warning: changed the `vFunc` function to allow the `gradient` param to be optional
Also wanted to discuss if we should maintain the `on` function props or if we should move to an event dispatcher approach
https://user-images.githubusercontent.com/25725586/175110015-1001ec69-f0ce-4b1b-997e-e445f7723e28.mp4
=> [@svelteui/core] Alert component

docs/src/includes/sidebar.md, docs/src/pages/core/notification.md, packages/svelteui-core/src/lib/components/Alert/Alert.styles.ts, packages/svelteui-core/src/lib/components/Alert/Alert.svelte, packages/svelteui-core/src/lib/components/Alert/index.ts, packages/svelteui-core/src/lib/components/Loader/loaders/Bars.svelte, packages/svelteui-core/src/lib/components/Loader/loaders/Circle.svelte, packages/svelteui-core/src/lib/components/Loader/loaders/Dots.svelte, packages/svelteui-core/src/lib/components/Loader/loaders/loader-props-extended.ts, packages/svelteui-core/src/lib/components/Notification/Notification.styles.ts, packages/svelteui-core/src/lib/components/Notification/Notification.svelte, packages/svelteui-core/src/lib/components/Notification/Notification.test.ts, packages/svelteui-core/src/lib/components/Notification/index.ts, packages/svelteui-core/src/lib/components/index.ts, packages/svelteui-core/src/routes/index.svelte, packages/svelteui-demos/src/lib/demos/core/Notification/Notification.demo.configurator.svelte, packages/svelteui-demos/src/lib/demos/core/Notification/Notification.demo.usage.svelte, packages/svelteui-demos/src/lib/demos/core/Notification/index.ts, packages/svelteui-demos/src/lib/index.ts
- docs
- demos
Also fixed the styling for the dark theme in Alert, since it was not 'reactive' (missing the dark themes, since createStyles is not called everytime the theme change, so the theme conditionals were useless, my bad).
https://user-images.githubusercontent.com/25725586/175540687-e5e4e4e6-5224-468f-995c-a2d1016577bf.mp4
=> [@svelteui/core] Notification

package-lock.json, packages/svelteui-composables/.prettierignore, packages/svelteui-core/.prettierignore, packages/svelteui-dates/.prettierignore, packages/svelteui-demos/.prettierignore, packages/svelteui-motion/.prettierignore, packages/svelteui-preprocessors/.prettierignore, packages/svelteui-preprocessors/package.json, packages/svelteui-prism/.prettierignore, packages/svelteui-tests/.prettierignore
Add `package-lock.json` to `prettierignore` files
=> [core]: add package-lock.json to prettierignore

docs/src/includes/sidebar.md, docs/src/pages/core/timeline.md, packages/svelteui-core/src/lib/components/Timeline/Timeline.styles.ts, packages/svelteui-core/src/lib/components/Timeline/Timeline.svelte, packages/svelteui-core/src/lib/components/Timeline/Timeline.test.ts, packages/svelteui-core/src/lib/components/Timeline/TimelineItem/TimelineItem.styles.ts, packages/svelteui-core/src/lib/components/Timeline/TimelineItem/TimelineItem.svelte, packages/svelteui-core/src/lib/components/Timeline/combinator.ts, packages/svelteui-core/src/lib/components/Timeline/index.ts, packages/svelteui-core/src/lib/components/index.ts, packages/svelteui-core/src/routes/index.svelte, packages/svelteui-dates/src/lib/components/CalendarBase/CalendarHeader/CalendarHeader.styles.ts, packages/svelteui-demos/src/lib/demos/core/Timeline/Timeline.demo.bullet.svelte, packages/svelteui-demos/src/lib/demos/core/Timeline/Timeline.demo.component.svelte, packages/svelteui-demos/src/lib/demos/core/Timeline/Timeline.demo.usage.svelte, packages/svelteui-demos/src/lib/demos/core/Timeline/index.ts, packages/svelteui-demos/src/lib/index.ts
- docs
- demos
https://user-images.githubusercontent.com/25725586/176705908-708ce9a0-1619-4a4b-bf7c-3319bb9e7963.mp4
=> [@svelteui/core] Timeline

packages/svelteui-prism/src/lib/dist/Prism/Prism.svelte
Force manual usage of Prism.
Related PRs:
* https://github.com/svelteuidev/svelteui/pull/140
* https://github.com/svelteuidev/svelteui/pull/120
=> [@svelteui/prism]: force manual usage of Prism

yarn.lock
Update yarn.lock with storybook changes.
=> [core]: update yarn.lock

packages/svelteui-demos/src/lib/demos/core/Affix/Affix.demo.usage.svelte, packages/svelteui-demos/src/lib/demos/core/AppShell/AppShell.demo.responsive.svelte, packages/svelteui-demos/src/lib/demos/core/AppShell/AppShell.demo.usage.svelte, packages/svelteui-demos/src/lib/demos/core/Badge/Badge.demo.width.svelte, packages/svelteui-demos/src/lib/demos/core/Card/Card.demo.usage.svelte, packages/svelteui-demos/src/lib/demos/core/Center/Center.demo.usage.svelte, packages/svelteui-demos/src/lib/demos/core/Divider/Divider.demo.label.svelte, packages/svelteui-demos/src/lib/demos/core/Divider/Divider.demo.size.svelte, packages/svelteui-demos/src/lib/demos/core/Divider/Divider.demo.usage.svelte, packages/svelteui-demos/src/lib/demos/core/Divider/Divider.demo.vertical.svelte, packages/svelteui-demos/src/lib/demos/core/Input/Input.demo.headless.svelte, packages/svelteui-demos/src/lib/demos/core/Kbd/Kbd.demo.example.svelte, packages/svelteui-demos/src/lib/demos/core/Modal/Modal.demo.sizes.svelte, packages/svelteui-demos/src/lib/demos/core/NativeSelect/NativeSelect.demo.binding.svelte, packages/svelteui-demos/src/lib/demos/core/NativeSelect/NativeSelect.demo.icon.svelte, packages/svelteui-demos/src/lib/demos/core/NumberInput/NumberInput.demo.externalcontrols.svelte, packages/svelteui-demos/src/lib/demos/core/ObserverRender/ObserverRender.demo.usage.svelte, packages/svelteui-demos/src/lib/demos/core/Overlay/Overlay.demo.blur.svelte, packages/svelteui-demos/src/lib/demos/core/Overlay/Overlay.demo.gradient.svelte, packages/svelteui-demos/src/lib/demos/core/Overlay/Overlay.demo.usage.svelte, packages/svelteui-demos/src/lib/demos/core/Popper/Popper.demo.configurator.svelte, packages/svelteui-demos/src/lib/demos/core/Tabs/Tabs.demo.override.svelte, packages/svelteui-demos/src/lib/demos/core/Text/Text.demo.gradient.svelte, packages/svelteui-demos/src/lib/demos/core/Timeline/Timeline.demo.bullet.svelte, packages/svelteui-demos/src/lib/demos/core/Timeline/Timeline.demo.component.svelte, packages/svelteui-demos/src/lib/demos/core/Timeline/Timeline.demo.usage.svelte, packages/svelteui-demos/src/lib/demos/core/Tooltip/Tooltip.demo.pointer.svelte
Simplify code examples in demos
=> [@svelteui/demos]: simplify code examples in demos

apps/docs/src/pages/core/menu.md, packages/svelteui-composables/src/test/shared/is.test.ts, packages/svelteui-core/src/components/Menu/Menu.svelte, packages/svelteui-core/src/components/Tabs/Tabs.svelte, packages/svelteui-demos/src/lib/demos/core/Menu/Menu.demo.control.svelte, packages/svelteui-demos/src/lib/demos/core/Menu/index.ts
* Support for custom control in Menu using slot approach
* Expose functions for Menu that allow the control of the menu state from outside the component
https://user-images.githubusercontent.com/25725586/184671026-8d8f4808-64f3-49dd-afc4-51c477c074ca.mp4
=> [@svelteuidev/core] Menu custom control

packages/svelteui-core/src/internal/utils/forwarding/forward-actions.ts
Fixes typing issue described in #116.
=> [@svelteui/core]: fix type inconsistency in actions API

packages/svelteui-core/src/components/Modal/Modal.svelte
Fix small bug in SvelteUIProvider that caused an error to appear.
Fixes #202
=> [@svelteui/core]: fix element retrieval in Modal

packages/svelteui-core/src/components/Switch/Switch.stories.svelte, packages/svelteui-core/src/components/Switch/Switch.svelte
Fixes #207.
* Added missing disabled prop for switch's input
* Added simple Switch stories
=> [@svelteui/core] Fixes #207: fix switch disabled behaviour

packages/svelteui-composables/package.json, packages/svelteui-core/package.json, packages/svelteui-dates/package.json, packages/svelteui-demos/package.json, packages/svelteui-motion/package.json, packages/svelteui-preprocessors/package.json, packages/svelteui-prism/package.json, packages/svelteui-tests/package.json, yarn.lock
=> [core]: bump svelte version

packages/svelteui-core/src/components/Menu/Menu.stories.svelte, packages/svelteui-core/src/components/Menu/Menu.svelte
=> [@svelteui/core]: Fix menu placement bug

apps/docs/src/includes/sidebar.md, apps/docs/src/pages/core/chip.md, apps/docs/svelte-docs.config.js, packages/svelteui-core/package.json, packages/svelteui-core/src/components/Chip/Chip.stories.svelte, packages/svelteui-core/src/components/Chip/Chip.svelte, packages/svelteui-core/src/components/Chip/ChipGroup/ChipGroup.stories.svelte, packages/svelteui-core/src/components/Chip/ChipGroup/ChipGroup.styles.ts, packages/svelteui-core/src/components/Chip/ChipGroup/ChipGroup.svelte, packages/svelteui-core/src/components/Menu/Menu.stories.svelte, packages/svelteui-core/src/components/Switch/Switch.svelte, packages/svelteui-core/src/components/index.ts, packages/svelteui-demos/src/demos/core/Chip/Chip.demo.configurator.svelte, packages/svelteui-demos/src/demos/core/Chip/Chip.demo.states.svelte, packages/svelteui-demos/src/demos/core/Chip/ChipGroup.demo.configurator.svelte, packages/svelteui-demos/src/demos/core/Chip/index.ts, packages/svelteui-demos/src/index.ts
* Docs for Chip
* Support for `multiple` in ChipGroup and other Group props
=> [docs]: Documentation for Chip and ChipGroup

CONTRIBUTING.md, apps/docs/package.json, packages/svelteui-composables/package.json, packages/svelteui-core/package.json, packages/svelteui-dates/package.json, packages/svelteui-demos/package.json, packages/svelteui-motion/package.json, packages/svelteui-preprocessors/package.json, packages/svelteui-prism/package.json, packages/svelteui-tests/package.json, yarn.lock
* Renamed docs prepare script to not be called by husky
* Fixed npm dependency errors for vite for npm - Fixes #221 
* Added Deno requirement to CONTRIBUTING guide
=> [core]: Fix npm dependency errors on install

apps/docs/package.json, packages/svelteui-core/src/components/Badge/Badge.stories.svelte, packages/svelteui-core/src/components/Chip/Chip.stories.svelte, packages/svelteui-demos/src/components/Configurator/controls/CompositeControl.svelte, packages/svelteui-demos/src/components/Configurator/controls/ControlsRenderer.svelte, packages/svelteui-prism/src/dist/Prism/Prism.styles.ts, yarn.lock
Fixes #225.
The problem was related to the way the `CompositeControl` component was dispatching the events.
Also fixed problem related to rollup setup in the docs, fixed a Prism prop type and added story to Badge.
Thank you to @Caladan08 for the investigation of the problematic components.
=> [@svelteuidev/demos] Fixes #225: Gradient problem in docs

packages/svelteui-core/src/components/Code/Code.styles.ts
=> [svelteuidev/core] Fixes #230: make Code props optional

apps/docs/src/components/homepage/Features.svelte, apps/docs/src/pages/index.md, packages/svelteui-core/src/components/Badge/Badge.stories.svelte
I have added a little animation on the `Features.svelte` component when we scroll (using the `IntersectionObserver`) and I also changed the line height of the text above the examples in the homepage to better match the line height used in `Features.svelte`
=> [docs]: Changed the line-height and added animations on scroll in the homepage

apps/docs/src/includes/sidebar.md, apps/docs/src/pages/composables/use-move.md, packages/svelteui-composables/src/actions/index.ts, packages/svelteui-composables/src/actions/use-lazy/use-lazy.ts, packages/svelteui-composables/src/actions/use-long-press/use-long-press.ts, packages/svelteui-composables/src/actions/use-move/index.ts, packages/svelteui-composables/src/actions/use-move/use-move.stories.svelte, packages/svelteui-composables/src/actions/use-move/use-move.ts, packages/svelteui-composables/src/shared/types/svelte-ui-composables-jsx.d.ts, packages/svelteui-composables/src/svelte-ui-composables-jsx.d.ts, packages/svelteui-core/src/components/Badge/Badge.stories.svelte, packages/svelteui-demos/src/demos/composables/actions/index.ts, packages/svelteui-demos/src/demos/composables/actions/use-move/index.ts, packages/svelteui-demos/src/demos/composables/actions/use-move/usage.svelte
* Added `use-move` action
* added respective story, demo and docs
* it was necessary to create a namespace for the new `HTMLAttributes` for the action, since it is important that these events can be triggered in HTML elements (not just Svelte components) - this is the most problematic part
=> [@svelteuidev/composables] use-move action

apps/docs/src/pages/core/native-select.md, packages/svelteui-core/src/components/NativeSelect/NativeSelect.stories.svelte, packages/svelteui-core/src/components/NativeSelect/NativeSelect.svelte, packages/svelteui-demos/src/demos/core/NativeSelect/NativeSelect.demo.objects.svelte, packages/svelteui-demos/src/demos/core/NativeSelect/index.ts
=> [docs]: added missing info for NativeSelect data if data is array of objects

packages/svelteui-core/src/components/Image/BackgroundImage/BackgroundImage.styles.ts, packages/svelteui-core/src/components/Image/Image.styles.ts
Related to https://github.com/svelteuidev/svelteui/issues/230#issuecomment-1368490754
=> [@svelteui/core]: make image props optional

packages/svelteui-core/src/components/TextInput/TextInput.svelte
Generate random id for input label
=> [@svelteui/core] Generate random id for input label in TextInput component

apps/docs/src/components/homepage/ComponentsExample.svelte, apps/docs/src/components/homepage/index.js, apps/docs/src/pages/index.md, apps/docs/src/theme.css, apps/docs/svelte-docs.config.js
This PR adds a section to the homepage where you can see some of the components in action. I'm not yet satisfied with the design but I wanted to see your opinion on this and if it can be made better
=> [docs]: Added some examples of components in the homepage

apps/docs/src/pages/theming/svelteui-provider.md
=> [docs]: remove outdated part about the config prop of SvelteUIProvider

packages/svelteui-core/src/components/ActionIcon/ActionIcon.stories.svelte, packages/svelteui-core/src/components/ActionIcon/ActionIcon.styles.ts, packages/svelteui-core/src/components/Button/Button.stories.svelte, packages/svelteui-core/src/styles/theme/utils/get-variant-theme/get-variant-theme.ts
fixes #297 
Not the cleanest solution, but fixes it for now
=> [@svelteui/core]: #297: fix disabled style in button

packages/svelteui-core/src/components/Radio/Radio.styles.ts, packages/svelteui-core/src/components/Radio/Radio.svelte, packages/svelteui-core/src/components/Tabs/Tab/Tab.svelte, packages/svelteui-core/src/components/Tabs/Tabs.d.ts, packages/svelteui-core/src/components/Tabs/Tabs.stories.svelte, packages/svelteui-core/src/components/Tabs/Tabs.svelte
Fixes https://github.com/svelteuidev/svelteui/issues/311.
Currently fixes the problem but it's something we will have to rethink in the future, I don't like the current approach all that much.
=> [@svelteui/core]: fix tabs to allow nested tabs

packages/svelteui-core/src/components/Menu/Menu.styles.ts, packages/svelteui-core/src/components/Menu/Menu.svelte, packages/svelteui-core/src/components/Menu/MenuItem/MenuItem.styles.ts
Hello, long time no see =)
I've noticed that keyboard navigation in Menu component doesn't work anymore.
Turns out it is related to styles changes.
=> Fix <Menu> keyboard navigation

apps/docs/src/lib/components/BottomNav.svelte, apps/docs/src/lib/components/Heading.svelte, apps/docs/src/lib/components/MinorHeading.svelte, apps/docs/src/lib/components/Sidebar.svelte, apps/docs/src/lib/components/TopBar/TopBar.svelte, apps/docs/src/lib/components/TopBar/data.ts, apps/docs/src/lib/components/mainpages/GettingStarted/Guides/Guides.svelte, apps/docs/src/lib/components/mainpages/GettingStarted/Installation/Card.svelte, apps/docs/src/lib/components/mainpages/MainLink.svelte, apps/docs/src/lib/components/mainpages/NextSteps.svelte, apps/docs/src/lib/pages/theming/ssr.md, apps/docs/src/lib/theme/styles/layout.css, apps/docs/src/lib/theme/ui/Sibling/Sibling.styles.js, apps/docs/src/lib/theme/ui/Sibling/Sibling.svelte, apps/docs/src/routes/+layout.svelte, packages/svelteui-core/src/components/Button/Button.stories.svelte, packages/svelteui-core/src/components/Button/Button.svelte, packages/svelteui-core/src/components/Input/Input.stories.svelte, packages/svelteui-core/src/components/NumberInput/NumberInput.stories.svelte
There were quite a few bugs with components and this fixes it
=> [docs]: Tweaks and fixes in dark theme

packages/svelteui-core/src/components/ActionIcon/ActionIcon.styles.ts, packages/svelteui-core/src/components/Collapse/Collapse.d.ts, packages/svelteui-core/src/components/Collapse/Collapse.stories.svelte, packages/svelteui-core/src/components/Collapse/Collapse.svelte, packages/svelteui-core/src/components/Collapse/Collapse.test.ts, packages/svelteui-core/src/components/Collapse/index.ts
New component `Collapse`, that allows for a section of content to collapse, occupying no space in the document. It will be useful for future component Accordion.
https://github.com/svelteuidev/svelteui/assets/25725586/380a1738-7836-4afa-a3c8-807f189c6917
=> [feat](@svelteui/core): Collapse component

apps/docs/src/lib/components/Sidebar.svelte, apps/docs/src/lib/data/main/homepage.js, apps/docs/src/routes/core/textarea/+page.md, packages/svelteui-core/src/components/Input/Input.d.ts, packages/svelteui-core/src/components/Input/Input.styles.ts, packages/svelteui-core/src/components/Input/Input.svelte, packages/svelteui-core/src/components/TextInput/TextInput.stories.svelte, packages/svelteui-core/src/components/Textarea/Textarea.d.ts, packages/svelteui-core/src/components/Textarea/Textarea.stories.svelte, packages/svelteui-core/src/components/Textarea/Textarea.svelte, packages/svelteui-core/src/components/Textarea/Textarea.test.ts, packages/svelteui-core/src/components/Textarea/index.ts, packages/svelteui-core/src/components/index.ts, packages/svelteui-demos/src/demos/core/Textarea/Textarea.demo.configurator.svelte, packages/svelteui-demos/src/demos/core/Textarea/Textarea.demo.disabled.svelte, packages/svelteui-demos/src/demos/core/Textarea/Textarea.demo.icon.svelte, packages/svelteui-demos/src/demos/core/Textarea/Textarea.demo.invalid.svelte, packages/svelteui-demos/src/demos/core/Textarea/Textarea.demo.rightsection.svelte, packages/svelteui-demos/src/demos/core/Textarea/index.ts, packages/svelteui-demos/src/index.ts
=> [@svelteui/core]: add Textarea component

apps/docs/src/lib/components/Sidebar.svelte, apps/docs/src/lib/data/main/homepage.js, apps/docs/src/routes/core/blockquote/+page.md, packages/svelteui-core/src/components/Blockquote/Blockquote.d.ts, packages/svelteui-core/src/components/Blockquote/Blockquote.stories.svelte, packages/svelteui-core/src/components/Blockquote/Blockquote.styles.ts, packages/svelteui-core/src/components/Blockquote/Blockquote.svelte, packages/svelteui-core/src/components/Blockquote/Blockquote.test.ts, packages/svelteui-core/src/components/Blockquote/QuoteIcon.svelte, packages/svelteui-core/src/components/Blockquote/index.ts, packages/svelteui-core/src/components/index.ts, packages/svelteui-demos/src/demos/core/Blockquote/Blockquote.demo.icon.svelte, packages/svelteui-demos/src/demos/core/Blockquote/Blockquote.demo.noicon.svelte, packages/svelteui-demos/src/demos/core/Blockquote/Blockquote.demo.usage.svelte, packages/svelteui-demos/src/demos/core/Blockquote/index.ts, packages/svelteui-demos/src/index.ts
=> [@svelteui/core] add Blockquote component
