svelteuidev/svelteui

packages/svelteui-actions/src/lib/index.ts
packages/svelteui-actions/src/lib/types/events.d.ts
packages/svelteui-actions/src/lib/use-download/use-download.ts

New action `use-download` that allows the download of a file (by using `Blob`) through the browser.

feat: use download action

---

packages/svelteui-utilities/.gitignore
packages/svelteui-utilities/package.json
packages/svelteui-utilities/src/lib/use-os/use-os.ts
packages/svelteui-utilities/src/test/example.test.ts
packages/svelteui-utilities/src/test/is.test.ts
packages/svelteui-utilities/src/test/random-id.test.ts
packages/svelteui-utilities/src/test/use-os.test.ts
packages/svelteui-utilities/svelte.config.js

Unit testing for `svelteui-utilities` package.
Also added extra conditionals to get extra info out of `getOs` (I only added since it was not recognizing my OS when running the tests).
How to run:
```
yarn test
yarn coverage
```
```
npm run test
npm run coverage
```

Unit testing for `svelteui-utilities`

---

packages/svelteui-core/src/lib/Button/Button.svelte
packages/svelteui-core/src/lib/_styles/SvelteUiGlobal.ts
packages/svelteui-core/src/lib/_styles/index.ts
packages/svelteui-core/src/routes/__layout.svelte
packages/svelteui-core/src/routes/index.svelte
packages/svelteui-core/stitches.config.ts

Focus ring similar to mantine's. 
By default visible only by keyboard navigation but with the possibility to configure this behavior.
Usage:
```javascript
css({
// possible variants: auto, always, never
focusRing: 'auto',
})
```
We need to figure out how to set the value for the focus ring once in configuration/theming.

Focus ring

---

packages/svelteui-actions/src/test/actions/use-page-leave.svelte
packages/svelteui-actions/src/test/actions/use-tab-leave.svelte
packages/svelteui-actions/src/test/use-page-leave.test.ts
packages/svelteui-actions/src/test/use-tab-leave.test.ts
packages/svelteui-utilities/src/test/is.test.ts
packages/svelteui-utilities/src/test/raf-fn.test.ts

Unit testing for:
- [utility] raf-fn
- [action] use-page-leave
- [action] use-tab-leave
Fix test for [utility] `sleep`, that could fail sometimes.

Unit test for new utiltities and actions

---

.gitignore
package-lock.json
package.json
packages/svelteui-actions/.gitignore
packages/svelteui-actions/.svelte-kit/tsconfig.json
packages/svelteui-core/.gitignore
packages/svelteui-core/.svelte-kit/tsconfig.json
packages/svelteui-motion/.gitignore
packages/svelteui-motion/.svelte-kit/tsconfig.json
packages/svelteui-prism/.gitignore
packages/svelteui-prism/.svelte-kit/tsconfig.json
packages/svelteui-prism/package.json
packages/svelteui-utilities/.gitignore
packages/svelteui-utilities/.svelte-kit/tsconfig.json
packages/svelteui-utilities/src/test/time.test.ts

Fixes to the time failing tests, that had setup problems as well:
* Use `utc` for time tests so that no timezone problems happen during their execution
* Bump `vitest` to solve error where a test suite was not being found
* Save `tsconfig.json` from `.svelte-kit` so that the test can be ran without running `npm run dev` before to generate the default `tsconfig.json` -> changes to all `.gitignores`

Fix failing unit tests

---

packages/svelteui-core/src/lib/components/Input/Input.svelte

Propagate `on:change` events in HTML elements used by `svelte:element`, since `bind:value` is not possible (by svelte design)
Example with the NativeSelect and a textarea:
https://user-images.githubusercontent.com/25725586/167213413-c1c9ea20-b1a7-498b-9338-0252bf96e686.mp4

[@svelteui/core] Propagate changes in value in `Input` component for <svelte:element>

---

packages/svelteui-core/src/lib/components/Checkbox/Checkbox.styles.ts
packages/svelteui-core/src/lib/components/Checkbox/Checkbox.svelte
packages/svelteui-core/src/lib/components/Checkbox/CheckboxGroup/CheckboxGroup.styles.ts
packages/svelteui-core/src/lib/components/Checkbox/CheckboxGroup/CheckboxGroup.svelte
packages/svelteui-core/src/lib/components/Checkbox/index.ts
packages/svelteui-core/src/lib/components/Group/Group.svelte
packages/svelteui-core/src/lib/components/InputWrapper/InputWrapper.svelte

Added checkbox group component.
**Decision taken**:
- It differs from the Mantine approach, for example, where the checkbox instead of being passed as slots, are built by the CheckboxGroup component, since this is the only way for it to access its children props.
- Due to the existence of a known limitation of svelte in the usage of `groups` in checkboxes - https://github.com/sveltejs/svelte/issues/2308 - another approach was taken (using the `on:change` and managing the checked entities inside CheckboxGroup)
https://user-images.githubusercontent.com/25725586/167257151-91da4673-f9a0-4627-bb63-2e8a539a8562.mp4
Example Code:
```
<script>
const items = [
{
value: "react",
label: "React"
},
{
value: "vue",
label: "Vue"
},
{
value: "svelte",
label: "Svelte"
}
];
let value = ["svelte"];
$: …
```

[@svelteui/core] Checkbox group

---

docs/src/pages/core/action-icon.md
docs/src/pages/core/button.md
docs/src/pages/core/code.md
docs/src/pages/core/image.md
docs/src/pages/core/loader.md
docs/src/pages/core/switch.md
docs/src/pages/core/text.md
docs/src/pages/core/title.md

Ported from the old docs the components:
* Button
* Code
* Loader
* ActionIcon + CloseButton
* Image + BackgroundImage
* Switch
* Text
* Title
Example of the button docs:

[docs] Port svelteui/core components from previous docs

---

docs/src/pages/actions/use-click-outside.md
docs/src/pages/actions/use-clipboard.md
docs/src/pages/actions/use-css-variable.md
docs/src/pages/actions/use-download.md
docs/src/pages/actions/use-focus.md
docs/src/pages/actions/use-page-leave.md
docs/src/pages/actions/use-tab-leave.md
docs/src/pages/core/action-icon.md
docs/src/pages/core/button.md
docs/src/pages/core/code.md
docs/src/pages/core/image.md
docs/src/pages/core/loader.md
docs/src/pages/core/switch.md
docs/src/pages/core/text.md
docs/src/pages/core/title.md

Ported actions from previous documentation:
* use-click-outside
* use-css-variable
* use-download
* use-focus
* use-page-leave
* use-tab-leave
Ported utilities from previous documentation:
* os
* rafFn
Also I formatted the code in components so that the spacing in the code is smaller on the left.

[docs]: port actions and utilities documentation

---

packages/svelteui-core/src/lib/components/Button/Button.svelte

Problem raised by @snake-345, in which the font size of the buttons was static and did not adapt with the size prop.
* adapt `fontSize` according to the prop `size`

[@svelteui/core] Adapt button font size based on the prop `size`

---

packages/svelteui-core/src/lib/components/Anchor/Anchor.styles.ts
packages/svelteui-core/src/lib/components/Anchor/Anchor.svelte
packages/svelteui-core/src/lib/components/Anchor/index.ts
packages/svelteui-core/src/lib/components/index.ts
packages/svelteui-core/src/routes/index.svelte

Added `Anchor` component. Basically works as a link to a href or can integrate with a routing library by passing another `root` and the required props. Receives the same props as `Text`
```svelte
<Anchor href="https://svelteui.org/">Main Page</Anchor>
<Anchor href="https://svelteui.org/" color='lime' size='lg'>Main Page</Anchor>
```
Docs will come in another PR

[@svelteui/core] Anchor

---

package.json
scripts/bump.ts
scripts/utils/version.ts

Added npm  script `bump:next` that supports bumping all packages to a next version.
Behaviour:
0.6.2 -> 0.6.2-next.1 | bump:next
0.6.2-next.1 -> 0.6.2-next.2 | bump:next
0.6.2-next.2  -> 0.6.3 | bump:patch
0.6.2-next.2  -> 0.7.0 | bump:minor
0.6.2-next.2  -> 1.0.0 | bump:major

[core] add 'next' support for bump script

---

package-lock.json
packages/svelteui-actions/package.json
packages/svelteui-core/package.json
packages/svelteui-dates/package.json
packages/svelteui-demos/package.json
packages/svelteui-motion/package.json
packages/svelteui-prism/package.json
packages/svelteui-utilities/package.json

* Fix imports in demos (and in other repos) when installing dependencies in the root repo
* It was related to the fact that the `@svelteuidev` folder content in node_modules was actually a symlink to the packages, so they were not in their transpiled form - not as they appear when they are normally installed as dependencies
* The fix was defining in each package package.json the `module: ./package/index.js` -> This will require running `npm run package` before starting development - not totally sure if there will be other problems regarding this change :warning: 
* Support for watching packages and having hot reload between packages. If we want to develop, for example, in `demos` but changing the components in `core` and seeing the changes in real time, it can be done now by running `npm …

[core] fix imports and support for watching

---

packages/svelteui-core/src/lib/components/Divider/Divider.errors.ts
packages/svelteui-core/src/lib/components/Divider/Divider.styles.ts
packages/svelteui-core/src/lib/components/Divider/Divider.svelte
packages/svelteui-core/src/lib/components/Divider/index.ts
packages/svelteui-core/src/lib/components/Text/Text.styles.ts
packages/svelteui-core/src/lib/components/index.ts
packages/svelteui-core/src/lib/stitches.config.ts
packages/svelteui-core/src/lib/styles/types/DefaultProps.ts
packages/svelteui-core/src/routes/index.svelte

* support for color, size and orientation control
* allows using a label string or using the slot `label` to override with more than strings - it is rendered inside a Text component
* shows an error if using orientation vertical with label - not supported
https://user-images.githubusercontent.com/25725586/169646626-fb3690de-0d2e-41de-b06f-3d2ebe5a156e.mp4
Code example:
```svelte
<Divider label="asdsd" labelPosition="right"/>
<Divider variant="dashed" labelPosition="center">
<Button slot="label" />
</Divider>
<Divider variant="dotted"/>
<Divider label="asdsd" labelPosition="right" labelProps={{ variant: "link", href: "https://svelteui.org", root: 'a' }}/>
<Divider size={10} />
<div style="height: 100px;">
<Divider size='md' color="red" orientation="vertical" />
</div>
```

[@svelteui/core] Divider component

---

packages/svelteui-core/src/lib/components/Popper/Popper.styles.ts
packages/svelteui-core/src/lib/components/Popper/Popper.svelte

1. Fix popper positioning problem due to scroll.
Reason: `getBoundingClientRect` only returns the positioning of the component taking into consideration the viewport being shown, so it is necessary to add the scroll delta.
https://user-images.githubusercontent.com/25725586/169710166-38d87c9a-194e-4e54-a6a2-7a8fb35dcdd0.mp4
2. Adapt popper positioning if it becomes hidden - on scroll, on resize, on mount and prop change
https://user-images.githubusercontent.com/25725586/169716762-d64f4112-0d87-4606-8945-49db5bc3092b.mp4
https://user-images.githubusercontent.com/25725586/169716763-d38274c5-8ee6-4e8c-ab23-e77700d7a0f6.mp4

[@svelteui/core] Adapt popper position if hidden (on scroll, resize, mount and prop change)

---

packages/svelteui-core/src/lib/components/Tooltip/Tooltip.svelte

* Pass element reference to popper
* Tweak arrow position in tooltip so that the arrow remains centered vertically (or horizontally if position is left/right)

[@svelteui/core] Pass tooltip slot element as ref to popper

---

packages/svelteui-actions/svelte.config.js

As a kind of :hammer: solution, the server option is not used when running tests - by using the env variable `VITEST` - in the svelte.config.json, which is used by the vitest config.

[@svelteui/actions] fix failing CI

---

packages/svelteui-core/src/lib/components/Input/Input.styles.ts
packages/svelteui-core/src/lib/components/Input/Input.svelte
packages/svelteui-core/src/lib/components/NumberInput/NumberInput.styles.ts
packages/svelteui-core/src/lib/components/NumberInput/NumberInput.svelte
packages/svelteui-core/src/lib/components/TextInput/TextInput.styles.ts
packages/svelteui-core/src/lib/components/TextInput/TextInput.svelte
packages/svelteui-core/src/lib/components/TextInput/index.ts
packages/svelteui-core/src/lib/components/index.ts
packages/svelteui-core/src/routes/index.svelte

* uses `InputWrapper` and `Input` components
* Workaround made for propagating the slot `rightSection`, which should not "appear" if the users of `TextInput` do not use it - this was made with the prop `showRightSection` in the `Input` which contains by default the previous behaviour.
* Modified `NumberInput` to use `TextInput` as base
```svelte
<TextInput 
placeholder='Your name'
description="Don't forget to add your full name"
label='Full name'
required
/>
<TextInput 
placeholder='Your name'
label='Full name'
size='lg'
on:input={() => { console.log(this.value) }}
/>
<TextInput
label="E-mail"
invalid
error="Invalid email"
rightSection={true}
rightSectionWidth={70}
>
<div slot='rightSection'>
<Text>@</Text>
</div>
</TextInput>
```
```svelte
<NumberInput
label="Your age"
min={0}
required …
```

[@svelteui/core] Text input

---

packages/svelteui-core/src/lib/components/NumberInput/NumberInput.svelte

Fixed problems with Number Input mentioned in https://github.com/svelteuidev/svelteui/pull/86#issue-1253046186

[@svelteui/core]: fix number input inconsistencies

---

scripts/pre-release.ts

Added to the `pre-release` script a new step that removes mentions of "local" packages, to be run before the publishing of the packages.
Also a small fix to the `preparePackages` function, which should be changing on the package.json of the sub package and not on the generated one.

[core] Pre release script for tsconfig changes

---

docs/src/includes/sidebar.md
docs/src/pages/core/anchor.md
docs/src/pages/core/number-input.md
docs/src/pages/core/paper.md
packages/svelteui-demos/src/lib/demos/core/Anchor/Anchor.demo.usage.svelte
packages/svelteui-demos/src/lib/demos/core/Anchor/index.ts
packages/svelteui-demos/src/lib/demos/core/Paper/Paper.demo.configurator.svelte
packages/svelteui-demos/src/lib/demos/core/Paper/index.ts
packages/svelteui-demos/src/lib/index.ts

Documentation and demos for components `Paper` and `Anchor`:
**Note**: I noticed that component `Paper` does not support controlling the `padding`, perhaps it is something we should support. If so, I can do it in this PR

[docs] Paper and anchor docs

---

docs/src/includes/sidebar.md
docs/src/pages/core/popper.md
packages/svelteui-core/src/lib/components/Popper/Popper.svelte
packages/svelteui-demos/src/lib/demos/core/Popper/Popper.demo.configurator.svelte
packages/svelteui-demos/src/lib/demos/core/Popper/index.ts
packages/svelteui-demos/src/lib/index.ts

Documentation for `Popper`
- Fix in popper where it should take into account the offset of its more direct parent in its position so that it always correctly positioned on its reference element.

[docs] Popper

---

.github/workflows/main.yml
package.json

* Fix failing CI by running the `package` command for tests before running the tests (it requires or else core does not have access to the testing package)
Tried only packaging the tests package, but composables is also required so I ended up packaging all, but perhaps later we only do those 2, since core will become heavier and can cost on the CI in terms of time.

[core]: run package for tests before running the tests (fixes failing CI)

---

packages/svelteui-core/src/lib/components/Card/Card.svelte
packages/svelteui-core/src/lib/components/Modal/Modal.svelte
packages/svelteui-core/svelte.config.js
packages/svelteui-demos/src/lib/demos/core/Checkbox/CheckboxGroup.demo.configurator.svelte
packages/svelteui-prism/svelte.config.js

* Add `radix-icons-svelte` to vite `deps` to fix failing tests for core and running `npm run dev` in prism package
* Fix linting problem in the `demos` package

[core]: add radix-icons-svelte to vite deps to fix core tests and prism

---

packages/svelteui-prism/src/lib/dist/Prism/Prism.svelte

So when I developed the initial prism solution, I did not noticed I was using two approaches of highlighting :facepalm:. We were using both the pre + code approach (which is automatic) and the manual API.
After thinking it was a svelte problem and opening an issue on their side - https://github.com/sveltejs/svelte/issues/7604 - it is actually not a svelte problem per say, but the pre + code approach is not compatible since Prism already removes the DOM nodes, and when updating the values svelte tries to remove them but they already are removed.
Since we were using both the automatic and the "manual" approach, the logic solution is to move only to the manual approach, which already work fine - this means removing the <code> tag (really needs to be removed because even with this tag but …

[@svelteui/prism]: fix prism error when updating code

---

packages/svelteui-composables/package.json
packages/svelteui-composables/src/test/actions/components/use-click-outside.svelte
packages/svelteui-composables/src/test/actions/components/use-clipboard.svelte
packages/svelteui-composables/src/test/actions/components/use-css-variable.svelte
packages/svelteui-composables/src/test/actions/components/use-download.svelte
packages/svelteui-composables/src/test/actions/components/use-focus.svelte
packages/svelteui-composables/src/test/actions/components/use-page-leave.svelte
packages/svelteui-composables/src/test/actions/components/use-tab-leave.svelte
packages/svelteui-composables/src/test/actions/example.test.ts
packages/svelteui-composables/src/test/actions/use-click-outside.test.ts
packages/svelteui-composables/src/test/actions/use-clipboard.test.ts
packages/svelteui-composables/src/test/actions/use-css-variable.test.ts
packages/svelteui-composables/src/test/actions/use-download.test.ts
packages/svelteui-composables/src/test/actions/use-focus.test.ts
packages/svelteui-composables/src/test/actions/use-page-leave.test.ts
packages/svelteui-composables/src/test/actions/use-tab-leave.test.ts
packages/svelteui-composables/src/test/shared/is.test.ts
packages/svelteui-composables/src/test/shared/random-id.test.ts
packages/svelteui-composables/src/test/shared/time.test.ts
packages/svelteui-composables/src/test/utilities/example.test.ts
packages/svelteui-composables/src/test/utilities/use-os.test.ts
packages/svelteui-composables/src/test/utilities/use-raf-fn.test.ts

Port tests from old utilities and actions packages to the composables package

[@svelteui/composables]: port old unit tests to the composables package

---

packages/svelteui-core/src/lib/styles/engine/create-styles.ts
packages/svelteui-core/src/lib/styles/theme/functions/fns/radius/radius.ts
packages/svelteui-core/src/lib/styles/theme/functions/fns/theme-color/theme-color.ts
packages/svelteui-core/src/routes/index.svelte

Falls back to default theme if no theme provider was used (meaning there is no theme saved in context).

[@svelteui/core]: fallback to default theme if no provider was used

---

docs/package-lock.json
docs/package.json
docs/prepare.ts
packages/svelteui-demos/src/lib/demos/core/Popper/Popper.demo.configurator.svelte

Temporary fix for the `process is undefined` problem in the docs for Popper + Tooltip, which resulted in a missing configuration in the Rollup config of svelte-docs, to use floating-ui.

[docs]: fix floating-ui problem with docs rollup config

---

packages/svelteui-core/src/lib/components/Popper/Popper.svelte

Between the `computePosition` start and its callback, the element might have been removed from DOM, so it might be null. A check was added to early return if that is the case.
Bug found by @LukasDoesDev and documented on discord.

[@svelteui/core]: add check for null element in popper

---

packages/svelteui-composables/src/lib/actions/use-hot-key/use-hot-key.ts

Fixes https://github.com/svelteuidev/svelteui/issues/143

[@svelteui/actions] fix duplicate event listeners on destroy in use-hot-key.ts

---

docs/src/includes/sidebar.md
docs/src/pages/core/menu.md
docs/src/pages/core/modal.md
packages/svelteui-core/src/lib/components/Menu/Menu.svelte
packages/svelteui-core/src/lib/components/Menu/MenuIcon.svelte
packages/svelteui-core/src/lib/components/Menu/MenuItem/MenuItem.styles.ts
packages/svelteui-core/src/lib/components/Menu/MenuItem/MenuItem.svelte
packages/svelteui-core/src/lib/components/Popper/Popper.styles.ts
packages/svelteui-core/src/lib/components/Popper/Popper.svelte
packages/svelteui-core/src/lib/internal/utils/get-transition/get-transition.ts
packages/svelteui-core/src/lib/styles/theme/functions/fns/variant/variant.ts
packages/svelteui-dates/package.json
packages/svelteui-demos/src/lib/demos/core/Menu/Menu.demo.custom.svelte
packages/svelteui-demos/src/lib/demos/core/Menu/Menu.demo.disabled.svelte
packages/svelteui-demos/src/lib/demos/core/Menu/Menu.demo.hover.svelte
packages/svelteui-demos/src/lib/demos/core/Menu/Menu.demo.position.svelte
packages/svelteui-demos/src/lib/demos/core/Menu/Menu.demo.size.svelte
packages/svelteui-demos/src/lib/demos/core/Menu/Menu.demo.styles.svelte
packages/svelteui-demos/src/lib/demos/core/Menu/Menu.demo.transition.svelte
packages/svelteui-demos/src/lib/demos/core/Menu/Menu.demo.usage.svelte
packages/svelteui-demos/src/lib/demos/core/Menu/index.ts
packages/svelteui-demos/src/lib/index.ts
packages/svelteui-preprocessors/.prettierignore
packages/svelteui-preprocessors/src/for-demos/preprocessors/SourceCode/SourceCode.svelte.d.ts

* Docs and demos for Menu
* Fixed position and placement in Menu and modified Menu to use transition logic already present in Popper (which was improved with some of the logic of Menu)
Note: Menu currently has no unit tests because an error was happening with them, will investigate it later
https://user-images.githubusercontent.com/25725586/178994781-7da4a544-5a6f-4bea-80e3-71fe846763f1.mov

[docs] Menu

---

docs/src/pages/core/button.md
packages/svelteui-core/src/components/Button/Button.styles.ts

Support `size` as number (as the prop type already allows) in Button
Fixes #164

[@svelteui/core]: support number as size in Button

---

packages/svelteui-core/src/components/Input/Input.styles.ts
packages/svelteui-core/src/components/Input/Input.svelte
packages/svelteui-core/src/components/NativeSelect/NativeSelect.svelte

Fixes #175.
The problem was related to the select logic + autocomplete.
- The select changes on the option is just to double check that the placeholder becomes selected when no value is provided (and a placeholder is provided).
- The autocomplete must be turned off for native select so that the previous option is not selected when reloading the page.
https://user-images.githubusercontent.com/25725586/182816649-cd90b478-793a-4f93-8fef-06653aaa2865.mov

[@svelteui/core]: fix select logic that showed previous selected option on reload

---

packages/svelteui-core/src/components/Tabs/Tabs.svelte

Fixes #179.
The error was due to the fact that Tabs handled the content of the tabs by injecting the tab content `innerHTML` into a container. TIL that when messing with `innerHTML`, the DOM loses all event handlers, so this was the problem
The solution was not using `innerHTML` and instead saving all the nodes on mount and then appending/replacing them when the tab is changed.

[@svelteui/core]: Fixes #179 - events inside tab contents are not propagated

---

packages/svelteui-core/src/components/Switch/Switch.styles.ts
packages/svelteui-core/src/components/Switch/Switch.svelte

Fixes #189.
* Fix switch disabled style
* Apply dark mode styles to switch

[@svelteui/core]: Fixes #189 - fix Switch disabled style and add dark styles

---

package.json
packages/svelteui-composables/package.json
packages/svelteui-composables/svelte.config.js
packages/svelteui-core/package.json
packages/svelteui-core/svelte.config.js
packages/svelteui-dates/package.json
packages/svelteui-dates/svelte.config.js
packages/svelteui-demos/package.json
packages/svelteui-demos/svelte.config.js
packages/svelteui-motion/package.json
packages/svelteui-motion/svelte.config.js
packages/svelteui-preprocessors/package.json
packages/svelteui-preprocessors/svelte.config.js
packages/svelteui-prism/package.json
packages/svelteui-prism/svelte.config.js
packages/svelteui-tests/package.json
packages/svelteui-tests/svelte.config.js
yarn.lock

Command `svelte-kit package` was deprecated in favor of a new package `@sveltejs/package` and script `svelte-package`. This PR contains this migration.
Links:
* https://kit.svelte.dev/docs/packaging
* https://github.com/sveltejs/kit/pull/5730

[core]: migrate to new svelte-package approach

---

apps/docs/src/pages/core/modal.md
packages/svelteui-demos/src/lib/demos/core/Modal/Modal.demo.usage.svelte

Since it is the most common question/doubt asked in Discord, perhaps it is best if we improve the `target` warning for Modal so that people that are using the demos examples can quickly see what is missing from the setup.
Now:<br>

[docs]: improve Modal target warning and demo

---

packages/svelteui-core/src/components/Tabs/Tab/Tab.styles.ts
packages/svelteui-core/src/components/Tabs/Tabs.stories.svelte

Fixed mentioned problem in Discord - https://discord.com/channels/954790377754337280/959831408988266506/1015295779117740112 - where the tabs text would not adapt to dark mode.

[@svelteui/core]: fix Tab dark mode color and simple story for testing

---

packages/svelteui-composables/package.json
packages/svelteui-core/package.json
packages/svelteui-dates/package.json
packages/svelteui-demos/package.json
packages/svelteui-motion/package.json
packages/svelteui-preprocessors/package.json
packages/svelteui-tests/package.json

**Problem:** Running `yarn format` changed the package.json - removing the `>=` from the svelte peerDependency, which causes errors when installing svelteui
**Solution:** Do not run prettier in package.json files, only in src/ files
Related to https://github.com/svelteuidev/svelteui/issues/205

[core]: fix prettier path to not apply changes in package.json peer dependencies

---

packages/svelteui-core/src/components/Chip/Chip.stories.svelte
packages/svelteui-core/src/components/Chip/Chip.styles.ts
packages/svelteui-core/src/components/Chip/Chip.svelte
packages/svelteui-core/src/components/Chip/Chip.test.ts
packages/svelteui-core/src/components/Chip/ChipGroup/ChipGroup.stories.svelte
packages/svelteui-core/src/components/Chip/ChipGroup/ChipGroup.styles.ts
packages/svelteui-core/src/components/Chip/ChipGroup/ChipGroup.svelte
packages/svelteui-core/src/components/Chip/ChipGroup/ChipGroup.test.ts
packages/svelteui-core/src/components/Chip/index.ts

Stubbed first draft of components. Not ready yet. Mostly copied from other components like Checkbox and also Mantine. Not tested.

[@svelteui/core]: add Chip and ChipGroup components

---

packages/svelteui-core/README.md
packages/svelteui-core/src/components/Menu/Menu.stories.svelte

The NPM package page had a template README, which made the package look like its not ready for use. 
See https://www.npmjs.com/package/@svelteuidev/core .
I have written some basic info in the README. This will at least help first time users and direct them to the website.

[docs] README documentation for NPM package

---

apps/docs/src/pages/basics.md

In the classes section of the "Learn the Basics" page, the <Button> component in the example is incorrectly closed and this fixes it.

[docs]: Fixed the closing tag in an example of classes

---

apps/docs/src/pages/theming/create-styles.md
apps/docs/src/pages/theming/ssr.md
apps/docs/src/pages/theming/svelteui-provider.md

a fix for #226 regarding old styled `__layout.svelte` files being replaced by `+layout.svelte`.

[docs] fix #226 - update outdated layout page naming

---

packages/svelteui-core/src/components/Alert/Alert.svelte
packages/svelteui-core/src/components/IconRenderer/IconRenderer.stories.svelte
packages/svelteui-core/src/components/IconRenderer/IconRenderer.styles.ts
packages/svelteui-core/src/components/IconRenderer/IconRenderer.svelte
packages/svelteui-core/src/components/IconRenderer/IconRendererUsage.stories.svelte
packages/svelteui-core/src/components/IconRenderer/index.ts
packages/svelteui-core/src/components/Input/Input.svelte
packages/svelteui-core/src/components/Menu/MenuItem/MenuItem.svelte
packages/svelteui-core/src/components/Notification/Notification.svelte
packages/svelteui-core/src/components/Tabs/Tab/Tab.svelte

The goal of this MR is to fill a gap of a piece of functionality that seems to be missing.
Currently in SvelteUI, multiple components that take a `icon` prop accept this as either a `Component` (a `SvelteComponentDev` type wrapper) or as a `HTMLOrSVGElement`. However, if a variable of type `HTMLOrSVGElement` is passed to one of these components, an error is returned as the icon is rendered using `<svelte:component/>`.
This MR adds a wrapper component called `IconRenderer` that is used in these various components and will check the type of the `icon` prop and then render it accordingly.

[@svelteui/core]: Add IconRenderer to various components that support `HTMLOrSVGElement` icon prop

---

apps/docs/src/components/Heading.svelte

Update header to fix link to docs page(s)
Noticed this while working on https://github.com/svelteuidev/svelteui/pull/235

[docs] fix links to docs in header (missing "/apps")

---

apps/docs/src/pages/theming/override.md

Add documentation showing how global styles can be used for targeted style overrides.
This doesn't really *solve* [#231](https://github.com/svelteuidev/svelteui/issues/231) but it does provide a work-around.

[docs] svelte global CSS for use in overrides

---

packages/svelteui-demos/src/components/Configurator/controls/SizeControl.svelte

Right now, in the Grow section of the Grid component, the Spacing field doesn't update its value when we change the option even through the option is reflected in the demo. This is what it looks like:
https://user-images.githubusercontent.com/94300963/206893939-70dc9ca2-b8ac-4708-9615-62c923cd0a36.mov
Most of the code in the GridDemo was built with the expectation that the Spacing field would be represented in a Slider component which made a few bugs with the current NativeSelect component. So, this commit fixes it

[@svelteui/demos] Fixed incorrect value being shown in GridDemo

---

packages/svelteui-core/src/components/Grid/Col/Col.styles.ts
packages/svelteui-core/src/components/Grid/Col/Col.svelte

Fixes problem mentioned in https://github.com/svelteuidev/svelteui/pull/247#issuecomment-1345638398.
* Fixed missing reactivity in spacing of the Grid
* Added spacing style in the Grid Col.

[@svelteuidev/core] Fix grid spacing

---

packages/svelteui-core/src/components/Menu/Menu.svelte

FIxes #217.
Due to the event forwarding logic, it was necessary to set the `open` and `close` events as exceptions. Probably in the future we will have to revisit the event forwarding logic.

[@svelteuidev/core] #217: fix menu open/close events not being dispatched

---

apps/docs/src/includes/sidebar.md
apps/docs/src/pages/composables/use-focus-trap.md
packages/svelteui-composables/src/actions/index.ts
packages/svelteui-composables/src/actions/use-focus-trap/index.ts
packages/svelteui-composables/src/actions/use-focus-trap/use-focus-trap.stories.svelte
packages/svelteui-composables/src/actions/use-focus-trap/use-focus-trap.ts
packages/svelteui-composables/src/actions/use-focus/use-focus.ts
packages/svelteui-core/src/components/Modal/Modal.svelte

Fixes #241.
* Action `focus-trap` that searches for a focusable child of a node and applies focus.
* respective story and docs

[@svelteuidev/composables] Fixes #241:  focus trap action and usage on modal

---

apps/docs/src/pages/core/anchor.md
packages/svelteui-core/src/components/Anchor/Anchor.styles.ts

Fixes #258.
* Made the anchor props optional since they have default values
* Added mention of the `root` and `external` props to the docs

[@svelteuidev/core] #258: Make Anchor props optional and complete docs

---

apps/docs/src/pages/core/tabs.md
packages/svelteui-core/src/components/Tabs/Tab/Tab.svelte
packages/svelteui-core/src/components/Tabs/Tabs.stories.svelte

* Added slot for icon and label in `Tabs.Tab`.
Feature request mentioned in Discord - https://discord.com/channels/954790377754337280/959831408988266506/1057663327343484958

[@svelteui/core]: Add slots for icon and label in `Tabs.Tab`

---

packages/svelteui-core/src/components/Popper/Popper.styles.ts

Solves https://github.com/svelteuidev/svelteui/issues/259 by removing the line of CSS that disables pointer events on the Popper.
It's unclear to me why pointer events are disabled, to begin with. Popper works perfectly fine with pointer-events enabled.  
Having the pointer-events allows having buttons and other interacting content inside the resulting popper container.
I'm unsure how to add reasonable tests for this change since it's a functional change but in CSS.

[@svelteui/core] Allow CSS pointer events in Popper

---

packages/svelteui-core/src/components/Chip/Chip.svelte
packages/svelteui-core/src/components/Chip/ChipGroup/ChipGroup.stories.svelte
packages/svelteui-core/src/components/Chip/ChipGroup/ChipGroup.styles.ts
packages/svelteui-core/src/components/Chip/ChipGroup/ChipGroup.svelte
packages/svelteui-core/src/components/Tabs/Tab/Tab.svelte

Prop `value` in `ChipGroup` will be `string[]` if `multiple` is true and `string` if `multiple` is false.
Originated from https://discord.com/channels/954790377754337280/959831408988266506/1058327568031436801

[@svelteui/core]: change ChipGroup `value` type based on `multiple` prop value

---

apps/docs/src/pages/core/tabs.md
packages/svelteui-core/src/components/Chip/ChipGroup/ChipGroup.stories.svelte
packages/svelteui-core/src/components/Tabs/Tab/Tab.styles.ts
packages/svelteui-core/src/components/Tabs/Tab/Tab.svelte

Related to https://github.com/svelteuidev/svelteui/pull/264?notification_referrer_id=NT_kwDOAYiKkrM1MTk1MzY3NzI2OjI1NzI1NTg2#issuecomment-1368184903.
- New prop `iconProps` in `Tabs.Tab` that allows passing props to IconRenderer (like color, etc).

[@svelteui/core]: Tabs.Tab `iconProps` prop

---

packages/svelteui-core/src/components/IconRenderer/IconRenderer.svelte

Checks to see if `HTMLElement` and `SVGElement` are defined before using them.

[@svelteui/core]: fix IconRenderer for SSR

---

packages/svelteui-core/src/components/Button/Button.styles.ts
packages/svelteui-core/src/components/IconRenderer/IconRenderer.svelte
packages/svelteui-core/src/components/Input/Input.styles.ts
packages/svelteui-core/src/components/TextInput/TextInput.styles.ts
packages/svelteui-core/src/components/TextInput/TextInput.svelte
packages/svelteui-core/src/styles/theme/types/DefaultProps.ts
packages/svelteui-core/src/styles/theme/types/index.ts

Fixes #275 in some components. A new migration to [component typings](https://github.com/sveltejs/language-tools/blob/master/docs/preprocessors/typescript.md#typing-components-authoring-packages) will be made.

[@svelteui/core]: Fixes #275: temporary fix for passing HTML attributes to components

---

packages/svelteui-core/src/components/Input/Input.svelte
packages/svelteui-core/src/components/NativeSelect/NativeSelect.stories.svelte
packages/svelteui-core/src/components/TextInput/TextInput.svelte
packages/svelteui-core/src/components/Title/Title.stories.svelte

Fixes #277.
The `use:forwardEvents` was propagating the event before the on:change call that changes the value, switching the order solved it.

[@svelteui/core] Fixes #277: Native select change event being called before the value is changed

---

apps/docs/src/pages/theming/ssr.md
packages/svelteui-core/src/styles/index.ts
packages/svelteui-core/src/styles/ssr.ts
packages/svelteui-core/src/styles/theme/SvelteUIProvider/SvelteUIProvider.svelte
packages/svelteui-core/src/styles/theme/SvelteUIProvider/index.ts
packages/svelteui-core/src/styles/theme/SvelteUIProvider/svelteui.provider.ts

Related to #172.
Pinging @impactvelocity since it's his solution and his opinion would be appreciated.
I'm not sure this is the best solution, leaving this here to open the discussion.
The current implementation would require that a user that wants to use SvelteUI with SSR would need to add to it's `hooks.server.ts` something like:
```
import { prepareStylesSSR } from '@svelteuidev/core';
export const handle = prepareStylesSSR;
``` 
or ```export const handle =  sequence(prepareStylesSSR); // if necessary to have more than one operation```.
Changes made:
* New util to add to hooks.server that allow correct loading of styles for SSR
* Removed `ssr` prop from SvelteUIProvider - the only way of doing SSR is with the approach above 
* Updated docs
Disclaimer: I'm no expert on this, would like …

[@svelteui/core]: #172: function to inject Stitches stylesheet as a hook (fixes SSR FOUC)

---

packages/svelteui-core/src/components/NativeSelect/NativeSelect.svelte

This PR fixes #283.
As pointed out in the related issue, it should use only `required` and not `aria-required`.

[@svelteui/core]: remove aria-required from NativeSelect

---

packages/svelteui-core/src/components/Tabs/Tabs.stories.svelte
packages/svelteui-core/src/components/Tabs/Tabs.styles.ts

Bug mentioned here: https://discord.com/channels/954790377754337280/1071565488066400347
- Added missing flex for tabs vertical orientation
- Added more stories to test this case

[@svelteui/core]: fix tabs vertical orientation flex

---

packages/svelteui-composables/src/actions/use-focus-trap/create-aria-hider.ts
packages/svelteui-composables/src/actions/use-focus-trap/scope-tab.ts
packages/svelteui-composables/src/actions/use-focus-trap/tabbable.ts
packages/svelteui-composables/src/actions/use-focus-trap/use-focus-trap.stories.svelte
packages/svelteui-composables/src/actions/use-focus-trap/use-focus-trap.ts
packages/svelteui-core/src/components/Input/Input.svelte
packages/svelteui-core/src/components/Modal/Modal.stories.svelte
packages/svelteui-core/src/components/Modal/Modal.svelte

Hello.
As I understand `focustrap` action was added as a placeholder.
Now it is actually a focus trap. I've converted Mantine's `use-focus-trap` with a more accurate setting of `aria-hidden` attributes.

Focus trap

---

packages/svelteui-composables/src/actions/use-clipboard/use-clipboard.ts
packages/svelteui-composables/test/actions/components/use-clipboard.svelte
packages/svelteui-composables/test/actions/use-clipboard.test.ts

Implementation for #348 allowing to set the clipboard text to a function, which is evaluated on click
```tsx
<button use:clipboard={() => `This text will be copied at ${new Date().toUTCString()}`}>Copy Me</button>
```

Allow dynamic values for use-clipboard action

---

packages/svelteui-core/src/styles/theme/SvelteUIProvider/SvelteUIProvider.svelte

Making `currentTheme` reactive, so the wrapper `div` class syncs up with the `html` class. Partially fixes #334

[fix](@svelteui/core): fix `dark-theme` class inconsistency

---

packages/svelteui-demos/src/demos/core/NativeSelect/NativeSelect.demo.objects.svelte

Added a disabled option to the NativeSelect example.
Closes #381

[docs]: add disabled option to NativeSelect sample

---

apps/docs/src/routes/core/switch/+page.md
packages/svelteui-core/src/components/Switch/Switch.d.ts
packages/svelteui-core/src/components/Switch/Switch.stories.svelte
packages/svelteui-core/src/components/Switch/Switch.styles.ts
packages/svelteui-core/src/components/Switch/Switch.svelte

While using inner labels (`onLabel` and `offLabel`) for the Switch component, I noticed that text was often moved further out of frame the longer it was, and that the size of font was unsuitable for emojies:
To fix this I added a new property to override `onLabel` and `offLabel` sizes called `innerLabelSize`. I also changed the `onLabel` CSS from `transform: translateX(-200%)` to `left: 10%` which mirrors the `offLabel` CSS of `right: 10%`.
Would love some feedback as my first contribution to this repo. Not too fussed if it's not suitable; it fixes my issue and thought I would share.

[@svelteui/core]: add Switch innerLabelSize property

---

packages/svelteui-demos/src/demos/core/PasswordInput/PasswordInput.demo.icon.svelte

I'm using PasswordInput component on my project when I saw this wrong import. I love SvelteUI and this is my first time contributing to open source ^_^.
```yarn prepush```

[docs]: fix PasswordInput import

---

packages/svelteui-core/src/components/InputWrapper/InputWrapper.svelte

ISSUES CLOSED: #475
This fixes a console warning `<LabelElement> was created with unknown prop 'htmlFor'` when using InputWrapper element.

`[@svelteui/core]: avoid passing an unknown prop htmlFor to LabelElement

---

apps/docs/src/routes/core/unstyled-button/+page.md

see Discord: https://discord.com/channels/954790377754337280/1257584599786061824/1257584599786061824
Link to the GitHub sourcecode file of UnstyledButton is wrong and now fixed.

[docs]: update link to code for UnstyledButton
